### ISSUE TITLE
checkpoint in "build_snp_list.R"

### ISSUE THREAD

**Issue by TriangularCell** [greenelab/tad_pathways_pipeline#13]
Hi gwaygenomics!
I found the checkpoint usd in "build_snp_list.R" is "2016-02-25", but in "install.R" the R libraries are installed under "2017-05-22". So I met some problems as can't load some libraries. Should it be "2017-05-22" in "build_snp_list.R"?

Thanks!

**Comment by gwaygenomics** [comment]
Thanks for reporting the issue @TriangularCell ! I am looking into this now.

`biomaRt` is the library of question correct? I believe a more permanent solution will be to move `biomaRt` versioning to conda. Based on the `sessionInfo.txt`, we need version `2.30.0`, while the current version is `2.32.1`. However, `2.30.0` is not currently an [available recipe in bioconda](https://bioconda.github.io/recipes.html). I filed a PR in bioconda/bioconda-recipes#5860 and will report back here once that is merged. Thanks again!

**Comment by gwaygenomics** [comment]
Thanks again @TriangularCell - I believe I address issues in #14 

please let me know if any other issues persist

**Comment by TriangularCell** [comment]
Yes it works! Thanks as well @gwaygenomics
